src/Entity/Consultant.php
<?php

namespace App\Entity;

use App\Entity\Trait\CivilityTrait;
use App\Repository\ConsultantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConsultantRepository::class)]
class Consultant
{
    use CivilityTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $lastname = null;

    #[ORM\Column(length: 150)]
    private ?string $firstname = null;

    #[ORM\OneToOne(inversedBy: 'consultant', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Offer.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\ExistsFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Entity\Trait\SlugTrait;
use App\Repository\OfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: OfferRepository::class)]
#[ApiResource(
    operations: [
        new Get(),
        new GetCollection()],
    normalizationContext: ['groups' => ['read']],
    order: ['published_at' => 'DESC'],
    paginationEnabled: true)]
#[ApiFilter(SearchFilter::class, properties: ['slug' => 'partial', 'City.label' => 'exact'])]
#[ApiFilter(ExistsFilter::class, properties: ['published_at'])]
class Offer
{
    use SlugTrait;

    #[Groups('read')]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups('read')]
    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[Groups('read')]
    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[Groups('read')]
    #[ORM\Column]
    private ?int $salary = null;

    #[Groups('read')]
    #[ORM\Column(length: 3)]
    private ?string $contrat_type = null;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[Groups('read')]
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $published_at = null;

    #[ORM\Column]
    private ?bool $published = null;

    #[ORM\Column]
    private ?bool $closed = null;

    #[Groups('read')]
    #[ORM\ManyToOne(inversedBy: 'offers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Recruiter $recruiter = null;

    #[ORM\OneToMany(mappedBy: 'offer', targetEntity: Application::class, orphanRemoval: true)]
    private Collection $applications;

    #[Groups('read')]
    #[ORM\Column]
    private ?int $positions = null;

    #[Groups('read')]
    #[ORM\ManyToOne(inversedBy: 'offers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?City $City = null;

    public function __construct()
    {
        $this->applications = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(int $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getContratType(): ?string
    {
        return $this->contrat_type;
    }

    public function setContratType(string $contrat_type): self
    {
        $this->contrat_type = $contrat_type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeImmutable $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function isClosed(): ?bool
    {
        return $this->closed;
    }

    public function setClosed(bool $closed): self
    {
        $this->closed = $closed;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getRecruiter(): ?Recruiter
    {
        return $this->recruiter;
    }

    public function setRecruiter(?Recruiter $recruiter): self
    {
        $this->recruiter = $recruiter;

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setOffer($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getOffer() === $this) {
                $application->setOffer(null);
            }
        }

        return $this;
    }

    public function getPositions(): ?int
    {
        return $this->positions;
    }

    public function setPositions(int $positions): self
    {
        $this->positions = $positions;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->City;
    }

    public function setCity(?City $City): self
    {
        $this->City = $City;

        return $this;
    }
}

src/Form/ConsultantType.php
<?php

namespace App\Form;

use App\Entity\Consultant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConsultantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('civility', ChoiceType::class, [
                'label' => 'Civilité',
                'expanded' => true,
                'multiple' => false,
                'choices' => [
                    'M.' => 'M.',
                    'Mme' => 'Mme',
                ],

            ])
            ->add('lastname', TextType::class)
            ->add('firstname', TextType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Consultant::class,
        ]);
    }
}

src/Controller/ConsultantController.php
<?php

namespace App\Controller;

use App\Repository\ApplicationRepository;
use App\Repository\CandidateRepository;
use App\Repository\OfferRepository;
use App\Repository\RecruiterRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/consultant', name: 'app_consultant')]
class ConsultantController extends AbstractController
{
    #[Route('/', name: '')]
    public function index(): Response
    {
        return $this->render('consultant/consultant.html.twig', [
            'controller_name' => 'ConsultantController',
        ]);
    }

    #[Route('/candidats-en-attente', name: '_pending_candidates')]
    public function showPendingCandidates(CandidateRepository $candidateRepository): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {

            $candidates = $candidateRepository->showPending();
        }

        return $this->render('consultant/pending_candidates.html.twig', [
            'candidates' => $candidates,
        ]);
    }

    #[Route('/recruteurs-en-attente', name: '_pending_recruiters')]
    public function showPendingRecruiters(RecruiterRepository $recruiterRepository): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {

            $recruiters = $recruiterRepository->showPending();
        }

        return $this->render('consultant/pending_recruiters.html.twig', [
            'recruiters' => $recruiters,
        ]);
    }

    #[Route('/validation-du-profil/{id}', name: '_validate_profile')]
    public function validateProfile(UserRepository $userRepository, int $id, Request $request, EntityManagerInterface $entityManager): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {

            $user = $userRepository->findOneBy(['id' => $id]);
            $user->setActive(true);

            $entityManager->persist($user);
            $entityManager->flush();
        }

        $route = $request->headers->get('referer');

        return $this->redirect($route);
    }

    #[Route('/offres-en-attente', name: '_pending_offers')]
    public function viewUnpublishedOffers(OfferRepository $offerRepository, Request $request, EntityManagerInterface $entityManager): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {
            $offers = $offerRepository->showUnpublished();
        }

        return $this->render('consultant/pending_offers.html.twig', [
            'offers' => $offers,
        ]);
    }

    #[Route('/publier-offre/{id}', name: '_validate_offer')]
    public function validateOffer(int $id, OfferRepository $offerRepository, Request $request, EntityManagerInterface $entityManager): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {

            $offer = $offerRepository->find($id);
            $offer->setPublished(true);
            $offer->setPublishedAt(new \DateTimeImmutable());
            $entityManager->persist($offer);
            $entityManager->flush();
        }

        $this->addFlash('success', 'L\'offre d\'emploi a bien été publiée.');
        $route = $request->headers->get('referer');

        return $this->redirect($route);
    }




    #[Route('/candidatures-en-attente', name: '_pending_applications')]
    public function viewPendingApplications(ApplicationRepository $applicationRepository): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {

            $applications = $applicationRepository->showUnsent();
        }

        return $this->render('consultant/pending_APPLICATIONS.html.twig', [
            'applications' => $applications,
        ]);
    }



    #[Route('/envoyer-candidature/{id}', name: '_validate_application')]
    public function validateApplication(int $id, MailerInterface $mailer,
         ApplicationRepository $applicationRepository,
         Request $request,
         EntityManagerInterface $entityManager): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {

            $application = $applicationRepository->find($id);
            $application->setSent(true);
            $application->setSentAt(new \DateTimeImmutable());
            $entityManager->persist($application);
            $entityManager->flush();

            $email = (new TemplatedEmail())
                ->from(new Address('consultant1@rhconseil.test',
                    'RH Conseil'))
                ->to($application->getCandidate()->getUser()->getEmail())
                ->subject('Votre candidature au poste de '
                    . $application->getOffer()->getTitle())
                ->htmlTemplate('email/application_sent_email.html.twig')
                ->context([
                    'candidate'=> $application->getCandidate(),
                    'offer' => $application->getOffer(),
                ]);
            $mailer->send($email);

            $applicationEmail = (new TemplatedEmail())
                ->from(new Address('consultant1@rhconseil.test',
                    'RH Conseil'))
                ->to($application->getOffer()->getRecruiter()->getUser()->getEmail())
                ->attachFromPath($application->getCandidate()->getResume()->getPath(),
                    'CV-'.$application->getCandidate()->getLastname())
                ->subject('Vous avez reçu une nouvelle candidature pour l\'offre : '
                    . $application->getOffer()->getTitle())
                ->htmlTemplate('email/application_email.html.twig')
                ->context([
                    'candidate'=> $application->getCandidate(),
                    'offer' => $application->getOffer(),
                ]);
            $mailer->send($applicationEmail);

        }

        $this->addFlash('success', 'La candidature a bien été transmise à l\'entreprise.');

        $route = $request->headers->get('referer');
        return $this->redirect($route);
    }

    #[Route('/refuser-candidature/{id}', name: '_decline_application')]
    public function declineApplication(int $id, Request $request, ApplicationRepository $applicationRepository, EntityManagerInterface $entityManager, MailerInterface $mailer): Response
    {
        if ($this->isGranted('ROLE_CONSULTANT')) {

            $application = $applicationRepository->find($id);
            $application->setSent(false);
            $application->setApproved(false);
            $entityManager->persist($application);
            $entityManager->flush();

            $email = (new TemplatedEmail())
                ->from(new Address('consultant1@rhconseil.test', 'RH Conseil'))
                ->to($application->getCandidate()->getUser()->getEmail())
                ->subject('Votre candidature au poste de ' . $application->getOffer()->getTitle())
                ->htmlTemplate('email/application_decline_email.html.twig')
                ->context([
                    'candidate'=> $application->getCandidate(),
                    'offer' => $application->getOffer(),
                ]);
            $mailer->send($email);


        }

        $this->addFlash('success', 'La candidature a bien été rejetée.');
        $route = $request->headers->get('referer');

        return $this->redirect($route);
    }


}

templates/consultant/consultant.html.twig
{% extends 'base.html.twig' %}

{% block title %}RH Conseil - Accueil consultant{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/apps/rh-conseil/src/Controller/ConsultantController.php'|file_link(0) }}">src/Controller/ConsultantController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/apps/rh-conseil/templates/consultant/admin.html.twig'|file_link(0) }}">templates/consultant/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/consultant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ConsultantController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/apps/rh-conseil/src/Controller/ConsultantController.php'|file_link(0) }}">src/Controller/ConsultantController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/apps/rh-conseil/templates/consultant/admin.html.twig'|file_link(0) }}">templates/consultant/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/consultant/pending_applications.html.twig
{% extends 'base.html.twig' %}

{% block title %}RH Conseil - Candidatures en attente de traitement{% endblock %}

{% block body %}

<div>
    <h1>Candidature en attente de traitement</h1>
    {% for application in applications %}
        <div>
            <h2>{{ application.candidate.lastname }} {{ application.candidate.firstname }}
                - {{ application.candidate.title }}</h2>
            <p>a postulé à l'offre de l'entreprise {{ application.offer.recruiter.name }}</p>
            <p>Poste à pourvoir : {{ application.offer.title }}</p>
            <a href="{{ asset(application.candidate.resume.path) }}" target="_blank">
                Voir le CV du candidat</a>

            <a href="{{ path('app_consultant_validate_application', {id: application.id }) }}">
                Transmettre la candidature</a>
            <a href="{{ path('app_consultant_decline_application', {id: application.id }) }}">
                Refuser la candidature</a>
        </div>
    {% endfor %}

</div>
{% endblock %}

templates/consultant/pending_candidates.html.twig
{% extends 'base.html.twig' %}

{% block title %}RH Conseil - Candidats en attente de validation{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Candidats en attente de validation</h1>
    {% for candidate in candidates %}
        <div>
            <p>{{ candidate.civility }} {{ candidate.lastname }} {{ candidate.firstname }}</p>
            <a href="{{ asset(candidate.resume.path) }}" target="_blank">Voir le CV</a>
            <a href="{{ path('app_consultant_validate_profile', {id: candidate.user.id }) }}">Valider le compte du candidat</a>

        </div>

    {% endfor %}

</div>
{% endblock %}

templates/consultant/pending_offers.html.twig
{% extends 'base.html.twig' %}

{% block title %}RH Conseil - Offres d'emploi en attente de publication{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Offres d'emploi en attente de publication</h1>
    {% for offer in offers %}
        <div>
            <h2>{{ offer.title }}</h2>
            <p>Nom de l'entreprise : {{ offer.recruiter.name }}</p>
            <p>{{ offer.description }}</p>
            <p>Type de contrat : {{ offer.contratType }}</p>
            <p>Salaire : {{ offer.salary }} €</p>
            <p>Nombre de postes à pourvoir : {{ offer.positions }}</p>

            <a href="{{ path('app_consultant_validate_offer', {id: offer.id }) }}">Publier l'offre d'emploi</a>
        </div>
    {% endfor %}

</div>
{% endblock %}

templates/consultant/pending_recruiters.html.twig
{% extends 'base.html.twig' %}

{% block title %}RH Conseil - Recruteurs en attente de validation{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Recruteurs en attente de validation</h1>
    {% for recruiter in recruiters %}
        <div>
            <p>{{ recruiter.name }}</p>
            <p>{{ recruiter.address }}</p>
            <p>{{ recruiter.city.zipcode }} - {{ recruiter.city.name }}</p>
            <a href="{{ path('app_consultant_validate_profile', {id: recruiter.user.id }) }}">Valider le compte du recruteur</a>

        </div>

    {% endfor %}

</div>
{% endblock %}